import { createFileRoute } from "@tanstack/react-router";
import { LegalDoc } from "@/components/askeasy/LegalDoc";

const TITLE = "Terms of Service — AskEasy";
const DESC =
  "The rules for using AskEasy: accounts, free limits, Pro subscription, acceptable use, AI output disclaimers and liability.";

export const Route = createFileRoute("/legal/terms")({
  head: () => ({
    meta: [
      { title: TITLE },
      { name: "description", content: DESC },
      { property: "og:title", content: TITLE },
      { property: "og:description", content: DESC },
      { property: "og:type", content: "article" },
      { property: "og:url", content: "https://askeasy.ai/legal/terms" },
    ],
    links: [{ rel: "canonical", href: "https://askeasy.ai/legal/terms" }],
  }),
  component: Terms,
});

function Terms() {
  return (
    <LegalDoc title="Terms of Service" updated="2026-08-26">
      <p>By using AskEasy at askeasy.ai you agree to these terms. If you do not agree, please don't use the service.</p>

      <h2>Your account</h2>
      <p>
        You need an account to save chats and subscribe. Keep your sign-in secure; you are responsible for activity
        under your account. You must be 13 or older, or use AskEasy with a parent or guardian.
      </p>

      <h2>Free tier and Pro</h2>
      <ul>
        <li>The free tier includes a daily allowance of text, media and voice messages, and access to standard models.</li>
        <li>Pro is ₹499 per month, billed through Cashfree, and unlocks unlimited messages and the Ultra model.</li>
        <li>Pro renews monthly until cancelled. You can cancel at any time from Settings; access continues to the end of the paid period.</li>
        <li>We may adjust prices or limits with notice on this page.</li>
      </ul>

      <h2>Acceptable use</h2>
      <ul>
        <li>No illegal activity, harassment, hate, sexual content involving minors, or attempts to harm others.</li>
        <li>No scraping, reselling, reverse-engineering, or bypassing usage limits.</li>
        <li>No uploading of content you don't have the right to share.</li>
        <li>Don't rely on AskEasy for medical, legal, or financial decisions.</li>
      </ul>
      <p>We may suspend accounts that break these rules.</p>

      <h2>AI output</h2>
      <p>
        Replies are generated by AI models and can be wrong, incomplete or out of date. Verify anything important. You
        own the prompts you write and the outputs you receive, to the extent permitted by the underlying model
        providers.
      </p>

      <h2>Connected actions</h2>
      <p>
        Where you connect an external service, AskEasy performs actions only after you approve them. You remain
        responsible for the actions you approve.
      </p>

      <h2>Availability</h2>
      <p>
        We aim for reliable service but do not guarantee uninterrupted availability. Features may change or be
        withdrawn.
      </p>

      <h2>Liability</h2>
      <p>
        AskEasy is provided "as is". To the maximum extent permitted by law, our total liability for any claim is
        limited to the amount you paid us in the three months before the claim.
      </p>

      <h2>Governing law</h2>
      <p>These terms are governed by the laws of India, with courts in India having jurisdiction.</p>

      <h2>Contact</h2>
      <p>
        Questions: <a href="mailto:support@askeasy.ai">support@askeasy.ai</a>
      </p>
    </LegalDoc>
  );
}
