/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OauthDebugRouteImport } from './routes/oauth-debug'
import { Route as BotsRouteImport } from './routes/bots'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as UpgradeSuccessRouteImport } from './routes/upgrade.success'
import { Route as ChatBotIdRouteImport } from './routes/chat.$botId'
import { Route as BotsNewRouteImport } from './routes/bots.new'
import { Route as BotsBotIdRouteImport } from './routes/bots.$botId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiToolsRouteImport } from './routes/api/tools'
import { Route as ApiCubixRouteImport } from './routes/api/cubix'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiBotGenerateRouteImport } from './routes/api/bot-generate'
import { Route as ChatBotIdThreadIdRouteImport } from './routes/chat.$botId.$threadId'
import { Route as ApiPublicCashfreeWebhookRouteImport } from './routes/api/public/cashfree-webhook'
import { Route as ApiPublicAnalyticsRouteImport } from './routes/api/public/analytics'
import { Route as ApiPublicOtpVerifyRouteImport } from './routes/api/public/otp/verify'
import { Route as ApiPublicOtpSendRouteImport } from './routes/api/public/otp/send'

const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthDebugRoute = OauthDebugRouteImport.update({
  id: '/oauth-debug',
  path: '/oauth-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsRoute = BotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const UpgradeSuccessRoute = UpgradeSuccessRouteImport.update({
  id: '/upgrade/success',
  path: '/upgrade/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatBotIdRoute = ChatBotIdRouteImport.update({
  id: '/chat/$botId',
  path: '/chat/$botId',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsNewRoute = BotsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BotsRoute,
} as any)
const BotsBotIdRoute = BotsBotIdRouteImport.update({
  id: '/$botId',
  path: '/$botId',
  getParentRoute: () => BotsRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsRoute = ApiToolsRouteImport.update({
  id: '/api/tools',
  path: '/api/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCubixRoute = ApiCubixRouteImport.update({
  id: '/api/cubix',
  path: '/api/cubix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotGenerateRoute = ApiBotGenerateRouteImport.update({
  id: '/api/bot-generate',
  path: '/api/bot-generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatBotIdThreadIdRoute = ChatBotIdThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatBotIdRoute,
} as any)
const ApiPublicCashfreeWebhookRoute =
  ApiPublicCashfreeWebhookRouteImport.update({
    id: '/api/public/cashfree-webhook',
    path: '/api/public/cashfree-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAnalyticsRoute = ApiPublicAnalyticsRouteImport.update({
  id: '/api/public/analytics',
  path: '/api/public/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOtpVerifyRoute = ApiPublicOtpVerifyRouteImport.update({
  id: '/api/public/otp/verify',
  path: '/api/public/otp/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOtpSendRoute = ApiPublicOtpSendRouteImport.update({
  id: '/api/public/otp/send',
  path: '/api/public/otp/send',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/bots': typeof BotsRouteWithChildren
  '/oauth-debug': typeof OauthDebugRoute
  '/onboarding': typeof OnboardingRoute
  '/splash': typeof SplashRoute
  '/api/bot-generate': typeof ApiBotGenerateRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cubix': typeof ApiCubixRoute
  '/api/tools': typeof ApiToolsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/bots/new': typeof BotsNewRoute
  '/chat/$botId': typeof ChatBotIdRouteWithChildren
  '/upgrade/success': typeof UpgradeSuccessRoute
  '/auth/': typeof AuthIndexRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/chat/$botId/$threadId': typeof ChatBotIdThreadIdRoute
  '/api/public/otp/send': typeof ApiPublicOtpSendRoute
  '/api/public/otp/verify': typeof ApiPublicOtpVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bots': typeof BotsRouteWithChildren
  '/oauth-debug': typeof OauthDebugRoute
  '/onboarding': typeof OnboardingRoute
  '/splash': typeof SplashRoute
  '/api/bot-generate': typeof ApiBotGenerateRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cubix': typeof ApiCubixRoute
  '/api/tools': typeof ApiToolsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/bots/new': typeof BotsNewRoute
  '/chat/$botId': typeof ChatBotIdRouteWithChildren
  '/upgrade/success': typeof UpgradeSuccessRoute
  '/auth': typeof AuthIndexRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/chat/$botId/$threadId': typeof ChatBotIdThreadIdRoute
  '/api/public/otp/send': typeof ApiPublicOtpSendRoute
  '/api/public/otp/verify': typeof ApiPublicOtpVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/bots': typeof BotsRouteWithChildren
  '/oauth-debug': typeof OauthDebugRoute
  '/onboarding': typeof OnboardingRoute
  '/splash': typeof SplashRoute
  '/api/bot-generate': typeof ApiBotGenerateRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cubix': typeof ApiCubixRoute
  '/api/tools': typeof ApiToolsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/bots/new': typeof BotsNewRoute
  '/chat/$botId': typeof ChatBotIdRouteWithChildren
  '/upgrade/success': typeof UpgradeSuccessRoute
  '/auth/': typeof AuthIndexRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/chat/$botId/$threadId': typeof ChatBotIdThreadIdRoute
  '/api/public/otp/send': typeof ApiPublicOtpSendRoute
  '/api/public/otp/verify': typeof ApiPublicOtpVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bots'
    | '/oauth-debug'
    | '/onboarding'
    | '/splash'
    | '/api/bot-generate'
    | '/api/chat'
    | '/api/cubix'
    | '/api/tools'
    | '/api/transcribe'
    | '/api/tts'
    | '/auth/callback'
    | '/bots/$botId'
    | '/bots/new'
    | '/chat/$botId'
    | '/upgrade/success'
    | '/auth/'
    | '/api/public/analytics'
    | '/api/public/cashfree-webhook'
    | '/chat/$botId/$threadId'
    | '/api/public/otp/send'
    | '/api/public/otp/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bots'
    | '/oauth-debug'
    | '/onboarding'
    | '/splash'
    | '/api/bot-generate'
    | '/api/chat'
    | '/api/cubix'
    | '/api/tools'
    | '/api/transcribe'
    | '/api/tts'
    | '/auth/callback'
    | '/bots/$botId'
    | '/bots/new'
    | '/chat/$botId'
    | '/upgrade/success'
    | '/auth'
    | '/api/public/analytics'
    | '/api/public/cashfree-webhook'
    | '/chat/$botId/$threadId'
    | '/api/public/otp/send'
    | '/api/public/otp/verify'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bots'
    | '/oauth-debug'
    | '/onboarding'
    | '/splash'
    | '/api/bot-generate'
    | '/api/chat'
    | '/api/cubix'
    | '/api/tools'
    | '/api/transcribe'
    | '/api/tts'
    | '/auth/callback'
    | '/bots/$botId'
    | '/bots/new'
    | '/chat/$botId'
    | '/upgrade/success'
    | '/auth/'
    | '/api/public/analytics'
    | '/api/public/cashfree-webhook'
    | '/chat/$botId/$threadId'
    | '/api/public/otp/send'
    | '/api/public/otp/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  BotsRoute: typeof BotsRouteWithChildren
  OauthDebugRoute: typeof OauthDebugRoute
  OnboardingRoute: typeof OnboardingRoute
  SplashRoute: typeof SplashRoute
  ApiBotGenerateRoute: typeof ApiBotGenerateRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCubixRoute: typeof ApiCubixRoute
  ApiToolsRoute: typeof ApiToolsRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ChatBotIdRoute: typeof ChatBotIdRouteWithChildren
  UpgradeSuccessRoute: typeof UpgradeSuccessRoute
  ApiPublicAnalyticsRoute: typeof ApiPublicAnalyticsRoute
  ApiPublicCashfreeWebhookRoute: typeof ApiPublicCashfreeWebhookRoute
  ApiPublicOtpSendRoute: typeof ApiPublicOtpSendRoute
  ApiPublicOtpVerifyRoute: typeof ApiPublicOtpVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-debug': {
      id: '/oauth-debug'
      path: '/oauth-debug'
      fullPath: '/oauth-debug'
      preLoaderRoute: typeof OauthDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots': {
      id: '/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof BotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/upgrade/success': {
      id: '/upgrade/success'
      path: '/upgrade/success'
      fullPath: '/upgrade/success'
      preLoaderRoute: typeof UpgradeSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$botId': {
      id: '/chat/$botId'
      path: '/chat/$botId'
      fullPath: '/chat/$botId'
      preLoaderRoute: typeof ChatBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/new': {
      id: '/bots/new'
      path: '/new'
      fullPath: '/bots/new'
      preLoaderRoute: typeof BotsNewRouteImport
      parentRoute: typeof BotsRoute
    }
    '/bots/$botId': {
      id: '/bots/$botId'
      path: '/$botId'
      fullPath: '/bots/$botId'
      preLoaderRoute: typeof BotsBotIdRouteImport
      parentRoute: typeof BotsRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools': {
      id: '/api/tools'
      path: '/api/tools'
      fullPath: '/api/tools'
      preLoaderRoute: typeof ApiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cubix': {
      id: '/api/cubix'
      path: '/api/cubix'
      fullPath: '/api/cubix'
      preLoaderRoute: typeof ApiCubixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot-generate': {
      id: '/api/bot-generate'
      path: '/api/bot-generate'
      fullPath: '/api/bot-generate'
      preLoaderRoute: typeof ApiBotGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$botId/$threadId': {
      id: '/chat/$botId/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$botId/$threadId'
      preLoaderRoute: typeof ChatBotIdThreadIdRouteImport
      parentRoute: typeof ChatBotIdRoute
    }
    '/api/public/cashfree-webhook': {
      id: '/api/public/cashfree-webhook'
      path: '/api/public/cashfree-webhook'
      fullPath: '/api/public/cashfree-webhook'
      preLoaderRoute: typeof ApiPublicCashfreeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analytics': {
      id: '/api/public/analytics'
      path: '/api/public/analytics'
      fullPath: '/api/public/analytics'
      preLoaderRoute: typeof ApiPublicAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/otp/verify': {
      id: '/api/public/otp/verify'
      path: '/api/public/otp/verify'
      fullPath: '/api/public/otp/verify'
      preLoaderRoute: typeof ApiPublicOtpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/otp/send': {
      id: '/api/public/otp/send'
      path: '/api/public/otp/send'
      fullPath: '/api/public/otp/send'
      preLoaderRoute: typeof ApiPublicOtpSendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BotsRouteChildren {
  BotsBotIdRoute: typeof BotsBotIdRoute
  BotsNewRoute: typeof BotsNewRoute
}

const BotsRouteChildren: BotsRouteChildren = {
  BotsBotIdRoute: BotsBotIdRoute,
  BotsNewRoute: BotsNewRoute,
}

const BotsRouteWithChildren = BotsRoute._addFileChildren(BotsRouteChildren)

interface ChatBotIdRouteChildren {
  ChatBotIdThreadIdRoute: typeof ChatBotIdThreadIdRoute
}

const ChatBotIdRouteChildren: ChatBotIdRouteChildren = {
  ChatBotIdThreadIdRoute: ChatBotIdThreadIdRoute,
}

const ChatBotIdRouteWithChildren = ChatBotIdRoute._addFileChildren(
  ChatBotIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  BotsRoute: BotsRouteWithChildren,
  OauthDebugRoute: OauthDebugRoute,
  OnboardingRoute: OnboardingRoute,
  SplashRoute: SplashRoute,
  ApiBotGenerateRoute: ApiBotGenerateRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCubixRoute: ApiCubixRoute,
  ApiToolsRoute: ApiToolsRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTtsRoute: ApiTtsRoute,
  ChatBotIdRoute: ChatBotIdRouteWithChildren,
  UpgradeSuccessRoute: UpgradeSuccessRoute,
  ApiPublicAnalyticsRoute: ApiPublicAnalyticsRoute,
  ApiPublicCashfreeWebhookRoute: ApiPublicCashfreeWebhookRoute,
  ApiPublicOtpSendRoute: ApiPublicOtpSendRoute,
  ApiPublicOtpVerifyRoute: ApiPublicOtpVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
